[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/jdgenerator/*" 
  to = "https://generatejobdescriptionandquestions.netlify.app/:splat"
  status = 200
  force = true

# Add a catch-all redirect at the end
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200