# netlify.toml for ai‑agents.talview.com
[build]
  publish = "build"          # or your existing output folder
  command = "npm run build"  # or your existing build command

[[redirects]]
  from   = "/jdgenerator/*"                                          # trap anything under /jdgenerator
  to     = "https://generatejobdescriptionandquestions.netlify.app/:splat"  
  status = 200               # 200 makes it a proxy/rewrite, not a browser redirect :contentReference[oaicite:0]{index=0}
  force  = true              # always proxy, even if a local file exists :contentReference[oaicite:1]{index=1}
