
[build]
  publish = "dist"         
  command = "npm run build" 

[[redirects]]
  from   = "/jd-generator/*"                                        
  to     = "https://generatejobdescriptionandquestions.netlify.app/:splat"
  status = 200               
  force  = true             

[[redirects]]
from   = "/question-generator/*"
to     = "https://questiongenerato.netlify.app/:splat"
status = 200
force  = true