[[redirects]]
  from   = "/jdgenerator"
  to     = "https://generatejobdescriptionandquestions.netlify.app"
  status = 200
  force  = true

[[redirects]]
  from   = "/jdgenerator/*"
  to     = "https://generatejobdescriptionandquestions.netlify.app/:splat"
  status = 200
  force  = true
