[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/jdgenerator/*"
  to = "https://generatejobdescriptionandquestions.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200