# netlify.toml for ai‑agents.talview.com
[build]
  publish = "build"         # or your existing output directory
  command = "npm run build" # or your existing build command

[[redirects]]
  from   = "/jdgenerator/*"                                        
  to     = "https://generatejobdescriptionandquestions.netlify.app/:splat"
  status = 200               
  force  = true             
